version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.12.0
    steps:
      - checkout
      - run:
          name: Install all the things
          command: npm ci
      - run:
          name: Test
          command: npm test
